// <auto-generated />
namespace QuanLyDeTaiKhoaHoc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addtableaccount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtableaccount));
        
        string IMigrationMetadata.Id
        {
            get { return "202103221558446_add-table-account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
